# Generated by Django 3.2.7 on 2021-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
