# Generated by Django 3.2.7 on 2021-09-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='price',
            field=models.FloatField(),
        ),
    ]
